name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install and Build
        run: |
          npm ci --force
          npm run lint
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
